var zamt="rf_dynamic_div20160824";var zaau="rf_save_button_id";var zaav="rf_div_tbar_save";var zaaw="rf_div_tbar_close";var zaax="rf_close_button_id";var zaay="rf_passcard_input_id";var zaaz="rf_folders_select_id";var zamu="rf_saveasbookmark_check_id";var zaba="rf_protect_chkbox_id";var zabb="rf_div_tbar_text";var zabc="rf_div_tbar_password";var zabd="rf_mp_savebtn";var zabe="rf_mp_checkbtn";var zabf="rf_masterpassconfirm_input";var zabg="rf_masterpass_input";var zabh="rf_mp_cancelbtn";var zamv=false;var zamw="rf_oq59tkMNhi";var zamx="rf_jfDmqrhZI0";var zamy="rf_mqoG2PsWe4";function zahh(){var zamz=zana();if(zamz==null){setTimeout(function(){zahh();}
,1500);return;}var zanb=document.getElementById(zamw);if(zanb){zanc({"name":"dialog_init"}
);}else{zand(zamz);}}function zand(zamz){var zane=document.createElement("link");zane.id="rf_7IiyJFZju5";zane.rel="stylesheet";zane.type="text/css";zane.href=chrome.runtime.getURL("content-dialog.css");document.head.appendChild(zane);var zanb=document.createElement("div");zanb.id=zamw;zanb.className="rf_3a5eQI5A3N";zanb.draggable="false";zanb.style.display="none";zanb.style.position="fixed";zamz.appendChild(zanb);var zanf=document.createElement("div");zanf.id=zamy;zanf.className="rf_530npRCcV5";zanf.draggable="false";zanb.appendChild(zanf);var zang=document.createElement("span");zang.id="rf_6e46jGA50S";zang.className="rf_X1eLm5Vxcx";zang.innerHTML="&times;";zang.draggable="false";zanf.appendChild(zang);var zjx=document.createElement("iframe");zjx.src=chrome.runtime.getURL("autosave-dialog.html");zjx.id=zamx;zjx.style.width="376px";zjx.style.height="300px";zjx.style.position="static !important";zjx.style.margin="0px !important";zjx.style.padding="0px !important";zjx.style.borderWidth="0px !important";zjx.style.visibility="visible !important";zjx.frameBorder=0;zjx.draggable="false";zjx.scrolling="no";zanb.appendChild(zjx);var zanh=document.createElement("script");zanh.src=chrome.runtime.getURL("content-dialog.js");document.head.appendChild(zanh);zanh.addEventListener("load",function(){zanh.parentNode.removeChild(zanh);}
);window.addEventListener('message',zani);}function zani(event){try{var data=JSON.parse(event.data);var zanb=$(zamw);if(!zanb){return;}
if(!data.hasOwnProperty("name")){return;}var zdm=chrome.runtime.getURL("").slice(0,-1);if(zdm!==event.origin&&data["name"]!=="rf_Pq4XBmSTzG"){return;}
var zgt=undefined;var zvt=0;var zamr=0;switch(data["name"]){case"update_dimensions":$(zamx).style.height=data["height"]+"px";$(zamx).style.width=data["width"]+"px";zgt=zanb.getBoundingClientRect();if(zgt.right>document.documentElement.clientWidth){zvt=document.documentElement.clientWidth-zgt.width;if(zvt<0){zvt=0;}
zanb.style.left=zvt+"px";}break;case"rf_Pq4XBmSTzG":case"close_dialog":zanb.style.visibility="hidden";zair({"name":"AutoSaveDialogClosed"}
);var zamz=zana();zamz.removeChild(zanb);break;case"dialog_ready":zgt=$(zamx).getBoundingClientRect();var zanj=$(zamy).getBoundingClientRect();if(data["bForcedSave"]){zvt=document.documentElement.clientWidth/2-zgt.width/2;zamr=document.documentElement.clientHeight/2-(zgt.height+zanj.height)/2;}
else{zvt=document.documentElement.clientWidth-zgt.width;zamr=0;}
if(zvt<0){zvt=0;}if(zamr<0){zamr=0;}zanb.style.left=zvt+"px";zanb.style.top=zamr+"px";zanb.style.visibility="visible";break;default:break;}
}catch(zdn){}}function zanc(message){$(zamx).contentWindow.postMessage(JSON.stringify(message),"*");}
function zana(){var zank=null;if(document.getElementsByTagName('body')[0]!=undefined){zank=document.getElementsByTagName('body')[0];}
if(!zank&&document.body){zank=document.body;zanl("GET document.body Body:"+zank);}
if(!zank){}return zank;}function zanm(event){var zann=document.getElementById(zabg);if(!zann.value.length){zann.focus();return;}
var zano=zann.getAttribute(zanp);var zanq=document.getElementById("rf_cache_mpwd_until_logut_chk").checked?true:false;if(zano=="passcardsaveresult"){var zga=document.getElementById(zaay);var zya=zga.value;var zanr=document.getElementById(zaaz);var zans=zanr.value;var zant={}
;zant[zanu]="passcardsaveresult";zant[zuv]=zann.value;zant[zanv]="AutoSaveDialogCheckMasterPassword";zant["NextAction"]="AutoSaveDialogSaveLogin";zant[zup]=!zamv?document.getElementById(zamu).checked:false;var zsd={}
;zsd[zus]=zans+"/"+zya;zant[zsf]=zsd;zant[zanw]=zanq;zair(zant);}
document.getElementById('td_mp_err_msg').innerHTML="";}
function zanx(zcm){try{var zany=zcm["name"];var zanz=zcm[zsl];var zaoa=zana();var zaob=zanz["Description"];var ztb=zanz["Code"];var zaoc=zanz[zanw];if(ztb==0){document.getElementById(zaay).focus();return;}
var zaod='auto';if(zac){zaod='220px';}if(ztb==zaoe){zaob=zaof("wrong_master_password");zaog(zaoa,zaob,zaod,zaof("Roboform_Master_Password"),zany,-1,zaoc);return;}
if(ztb==zaoh){if(document.getElementById(zabc)!=null){zaoa.removeChild(document.getElementById(zabc));}
document.getElementById(zamt).style.opacity="0.6";document.getElementById(zaay).disabled=true;document.getElementById(zaaz).disabled=true;document.getElementById(zaau).disabled=true;document.getElementById(zaax).disabled=true;var zaoi=document.createElement('div');zaoi.id=zabc;var zaoj='<fieldset style="padding:0; margin:0; margin-right:5px;margin-left:5px;margin-top:5px; border:1px solid #898989; background-color:#F3F3F3; color:RGB(70,70,70);font-family: tahoma;font-size:            12px;font-weight:normal; width:318px; max-width: 318px; min-width:318px; border-radius:5px;"  id="rfMPsection_groupbox">';zaoj+='<legend  style="text-align:auto;padding: 0; margin:0; color:#123272;font-family:tahoma;font-size:12px;font-weight:bold;display:block;margin-left:7px;width:220px;text-indent:1px;background-color:#F3F3F3;"  id="rfMPsection_legend">'+zaof("savebar_createmp_caption")+'</legend>';zaoj+='<table id="rfMPsection_toptable" cellpadding="0" cellspacing="0" border="0" width="100%">';zaoj+='<tr><td align="left" style="padding-left:5px;">'+zaof("savebar_createmp_text1")+' <br />'+zaof("savebar_createmp_text2")+'</td></tr>';zaoj+='<tr><td align="left" style="padding-left:5px;color:red;font-size:10px;" id="td_create_mp_err_msg"></td></tr></table>';zaoj+='<table id="rfMPsection_toptable1" cellpadding="0" cellspacing="0" border="0" width="100%">';zaoj+='<tr><td style="padding-left:5px;font-weight:bold;" align="left" nowrap>'+zaof("savebar_createmp_password")+'</td>';zaoj+='<td align="right" style="text-align:right;padding-right:5px;"><input id="'+zabg+'" type="password" maxlength="80" value=""/></td></tr>';zaoj+='<tr><td align="left" nowrap style="font-weight:bold;padding-left:5px;padding-top:5px;">'+zaof("savebar_createmp_confirm")+'</td><td align="right" style="padding-right:5px;padding-top:5px;text-align:right;">';zaoj+='<input  id="'+zabf+'" type="password" maxlength="80" value=""/></td></tr>';zaoj+='<tr><td nowrap colspan="2" align="right" style="padding-top:5px;padding-bottom:4px;padding-right:5px;text-align:right;">';zaoj+='<input id="'+zabd+'" type="button" name="submitClicked" value="'+zaof("savebar_save_btn")+'" /> ';zaoj+='<input type="button" id="'+zabh+'" value="'+zaof("cancel_btn")+'" /></td></tr></table></fieldset>';zaoi.innerHTML=zaoj;zaoi.style.visibility="visible";zaoa.appendChild(zaoi);document.getElementById(zabh).addEventListener("click",zaok,false);document.getElementById(zabd).addEventListener("click",zaol,false);document.getElementById(zabf).addEventListener("keypress",zaom,false);document.getElementById(zabg).focus();zaoi.style.border="2px solid #ccc";zaoi.style.borderRadius="5px";zaoi.style.boxShadow="6px 6px 5px #888";return;}
if(ztb==zaon){alert(zaof("err_object_already_exists"));}
}catch(zhj){}}
