// Copyright (C) 1999-2017 Siber Systems Inc. All Rights Reserved.
var RfapiJS=RfapiJS||{}
;(function(){var zffr="1.17.5.4";var zak="May 4, 2017";var zcte=RfapiJS["traceJS"];var zctf=RfapiJS["traceLevel"];var zfpw=RfapiJS["RfApiError"];var zfpx=RfapiJS["EnDataItemInfoParts"];var zfhs=RfapiJS["RfErrType"];var zcue=RfapiJS["HTTP_Status_Code_OK"];var zfpy=RfapiJS["RfUrlMatchLevel"];var ztk=RfapiJS["EnRfDataItemType"];var zawd=RfapiJS["utils"];var zfht=RfapiJS["UserDataFiles"];var zfpz=RfapiJS["EnUsageInfoList"];var zavo=RfapiJS["UTF8"];var zwe=RfapiJS["logJS"];var zwf="repository.js";var zfqa=["United States","Afganistan","Andorra","Argentina","Armenia","Australia","Austria","Belarus","Belgium","Bolivia","Bosnia And Herzegovina","Brazil","Bulgaria","Canada","Chile","China","Colombia","Costa Rica","Croatia","Cyprus","Czech Republic","Denmark","Egypt","Estonia","Finland","France","Gabon","Germany","Gibraltar","Greece","Greenland","Haiti","Hungary","Hong Kong","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Kazakhstan","Korea","Latvia","Liechtenstein","Lithuania","Luxembourg","Macedonia","Malaysia","Malta","Mexico","Moldova","Monaco","Montenegro","Morocco","Namibia","Netherlands","New Zealand","Nigeria","Norway","Pakistan","Panama","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russia","San Marino","Saudi Arabia","Serbia","Singapore","Slovakia","Slovenia","South Africa","Spain","Sweden","Switzerland","Taiwan","Thailand","Turkey","Ukraine","United Kingdom","Venezuela","Vietnam"];RfapiJS.ITEMINFO_MODTIME_PROP="mod";RfapiJS.ITEMINFO_CREATETIME_PROP="cre";RfapiJS.ITEMINFO_SIZE_PROP="size";RfapiJS.ITEMINFO_PATH_PROP="path";RfapiJS.ITEMINFO_TYPE_PROP="type";RfapiJS.ITEM_ISDEFAULT_PROP="d";RfapiJS.FIELD_CAPTION_PROP="c";RfapiJS.FIELD_VALUE_PROP="v";RfapiJS.FIELD_TYPE_PROP="t";RfapiJS.ITEM_GOTOURL_PROP="g";RfapiJS.ID_OPTIONS_PROP="o";RfapiJS.ID_GROUPS_PROP="g";RfapiJS.ID_INSTANCES_PROP="i";RfapiJS.ITEM_NAME_PROP="n";RfapiJS.ITEM_NOTE_PROP="n";RfapiJS.ITEMDATA_FIELDS_PROP="f";RfapiJS.ITEMDATA_BLOCK_PROP="b";RfapiJS.ITEM_INFO_PROP="i";RfapiJS.ITEM_ISFOLDER_PROP="F";RfapiJS.ITEM_BODY_PROP="b";RfapiJS.ITEM_CHILDS_PROP="c";RfapiJS.ITEM_CRETIME_PROP="c";RfapiJS.ITEM_MODTIME_PROP="m";RfapiJS.ITEM_MATCHURL_PROP="m";RfapiJS.ITEM_ENCODED_PROP="e";RfapiJS.ITEM_SHARED_PROP="Shared";RfapiJS.ROOT_NODE="root";RfapiJS.ACCOUNT_ID_PROP="accountId";RfapiJS.NAME_PROP="name";RfapiJS.SENDER_PROP="sender";RfapiJS.SENDERNAME_PROP="senderName";RfapiJS.ACCOUNTINFO_PROP="accountInfo"
var zfqb="[R] Item not found: ";var zfqc="[R] Folder not found: ";var zfqd="[R] Parent folder not found: ";var zfqe="[R] Cannot create, Unknown item type: ";var zfqf="[R] Folder already exists: ";var zfqg="[R] Invalid path: ";var zfqh="[R] Wrong parameter: ";var zfhx="undefined";var zfqi=[ztk["RfItemType_Login"],ztk["RfItemType_Bookmark"],ztk["RfItemType_SearchCard"],ztk["RfItemType_BlockingPasscard"],ztk["RfItemType_Identity"],ztk["RfItemType_Contact"],ztk["RfItemType_Safenote"],ztk["RfItemType_Folder"]];var zfqj={"RepoErr_None":0,"RepoErr_NoParentFolder":1,"RepoErr_ItemAlreadyExists":3,"RepoErr_UnknownItemType":4,"RepoErr_NotFound":17,"RepoErr__Last":1000
}
;var zfqk="m_lFields";var zfql="Use for Form Filling";var zfqm="App Upload";var zfqn="Phone prefix mode";var zfqo="m_sName";var zfqp="s";var zfqq="s";var zfqr="p";var zfqs="url";var zfqt="deep";var zfqu="request";var zfqv="parts";var zfqw="gotoUrl";var zfqx="matchUrl";var zfqy="iconMime";var zfqz="folder";var zfra="level";var zfrb="Fields";var zfrc="isMainFrame";var zfrd="pwd";var zfre="appUpload";var zfrf="phonePrefixMode";var zfrg="";var zfrh="GetMatchingPasscards";var zfri="GetDomainPasscards";var zfrj="GetItemsCount";var zfrk="GetUsageInfo";var zfrl="GetItemInfo";var zfrm="GetFile";var zfrn="Search";var zfro="CreateDataItem";var zfrp="GetDataItem";var zfrq="DeleteAllObjects";var zfrr="CreateFolder";var zfrs="DeleteObject";var zfrt="CopyObject";var zfru="MoveObject";var zfrv="PutDataItem";var zfrw="GetItemsList";function zfrx(){this.zfry=null;this.zfrz={}
;this.zfsa={};this.zfsb="";};zfrx.prototype.zdwm=function(){this.zfry=null;this.zfrz={}
;this.zfsa={};this.zfsb="";};zfrx.prototype.zfsc=function(zfsd){this.zfsb=zfsd;}
;zfrx.prototype.zfse=function(zasi,zfsd){if(!this.zfrz[zfsd]){return null;}
return this.zfrz[zfsd][zasi];};zfrx.prototype.zauy=function(data,zasi,zfsd){zcte("Repository.setData ->  accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);this.zfsf(zfsd,zasi);var zfsg=[];var zfir=this.zfrz[zfsd];if(!zfir){this.zfrz[zfsd]={}
;}this.zfrz[zfsd][zasi]=data;if(zasi==zfht["USER_DATA"]){if(this.zfsb==zfsd){var zgh=data[RfapiJS.ITEM_CHILDS_PROP];if(!zgh){throw"Wrong user account data format[1]: Account='"+zfsd+"'  [i]='"+data[RfapiJS.ITEM_INFO_PROP]+"' [c]='"+data[RfapiJS.ITEM_CHILDS_PROP]+"'";}
var zfsh=null;for(var zcw=0;zcw<zgh.length;zcw++){if(zgh[zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==RfapiJS.ROOT_NODE){zfsh=zgh[zcw];break;}
}if(!zfsh){var zfsi={};zfsi[RfapiJS.ITEM_ISFOLDER_PROP]=true;zfsi[RfapiJS.ITEM_NAME_PROP]=RfapiJS.ROOT_NODE;zfsh={}
;zfsh[RfapiJS.ITEM_INFO_PROP]=zfsi;zfsh[RfapiJS.ITEM_CHILDS_PROP]=[];zgh.push(zfsh);}
if(typeof zfsh[RfapiJS.ITEM_CHILDS_PROP]==zfhx){zfsh[RfapiJS.ITEM_CHILDS_PROP]=[];}
if(!this.zfsa[RfapiJS.ITEM_INFO_PROP]){this.zfsj();}
if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP]){for(var zcds=0;zcds<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zcds++){if(!this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zcds][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){this.zfsa[RfapiJS.ITEM_CHILDS_PROP].splice(zcds,1);zcds--;}
}}if(typeof zfsh[RfapiJS.ITEM_CHILDS_PROP]!=zfhx){for(var zcw=0;zcw<zfsh[RfapiJS.ITEM_CHILDS_PROP].length;zcw++){var zfb=zfsh[RfapiJS.ITEM_CHILDS_PROP][zcw];var zfsk=this.zfsl(zfb);for(var zck in zfsk){zfsg[zck]=zfsk[zck];}
zawd.zfsm(zfb,this.zfsa[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);}
}}else{var zfsn=data[RfapiJS.ITEM_CHILDS_PROP];if(!zfsn){throw"Wrong shared account data format[1]: Account='"+zfsd+"'  [i]='"+data[RfapiJS.ITEM_INFO_PROP]+"' [c]='"+data[RfapiJS.ITEM_CHILDS_PROP]+"'";}
var zfso=null;for(var zcw=0;zcw<zfsn.length;zcw++){if(zfsn[zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==RfapiJS.ROOT_NODE){zfso=zfsn[zcw];break;}
}if(!zfso){var zfsp={};zfsp[RfapiJS.ITEM_ISFOLDER_PROP]=true;zfsp[RfapiJS.ITEM_NAME_PROP]=RfapiJS.ROOT_NODE;zfso={}
;zfso[RfapiJS.ITEM_INFO_PROP]=zfsp;zfso[RfapiJS.ITEM_CHILDS_PROP]=[];zfsn.push(zfso);}
if(!this.zfsa[RfapiJS.ITEM_INFO_PROP]){this.zfsj();}
for(var zgg=0;zgg<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zgg++){var zgk=this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zgg];if(zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]&&zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP]==zfsd){zgk[RfapiJS.ITEM_CHILDS_PROP]=typeof zfso[RfapiJS.ITEM_CHILDS_PROP]==zfhx?[]:zfso[RfapiJS.ITEM_CHILDS_PROP];break;}
}}}return zfsg;};zfrx.prototype.zfsq=function(zfsd){if(!zfsd){return this.zfsa;}
var zvd=null;var zfsr=this.zfse(zfht["USER_DATA"],zfsd)[RfapiJS.ITEM_CHILDS_PROP];for(var zcw=0;zcw<zfsr.length;zcw++){if(zfsr[zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==RfapiJS.ROOT_NODE){zvd=zfsr[zcw];break;}
}return zvd;};zfrx.prototype.zfss=function(zfsd){var zfst=this.zfsq()[RfapiJS.ITEM_CHILDS_PROP];var zfsu=this.zfsq(zfsd);zfsu[RfapiJS.ITEM_CHILDS_PROP]=[];if(zfst){for(var zcw=0;zcw<zfst.length;zcw++){var zgk=zfst[zcw];var zfsv=zgk[RfapiJS.ITEM_INFO_PROP];if(zfsd==this.zfsb){if(zfsv[RfapiJS.ITEM_SHARED_PROP]){continue;}
zfsu[RfapiJS.ITEM_CHILDS_PROP].push(zgk);}else{if(!zfsv[RfapiJS.ITEM_SHARED_PROP]||(zfsd!=zfsv[RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP])){continue;}
for(var zgg=0;zgg<zgk[RfapiJS.ITEM_CHILDS_PROP].length;zgg++){zfsu[RfapiJS.ITEM_CHILDS_PROP].push(zgk[RfapiJS.ITEM_CHILDS_PROP][zgg]);}
}}}};zfrx.prototype.zfsl=function(zfb){var zfsw=1;var zfsx=[];for(var zgg=0;zgg<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zgg++){var zfsy=this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zgg];if(zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){var zfsz=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP];if(!zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){if(zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==zfsz[RfapiJS.NAME_PROP]){if(zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]){var sender=zfsz[RfapiJS.SENDERNAME_PROP]?zfsz[RfapiJS.SENDERNAME_PROP]:(zfsz[RfapiJS.SENDER_PROP]?zfsz[RfapiJS.SENDER_PROP]:this.zfsb);var zfta=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+" ("+sender+")"
zcte("Repository.checkDuplicateFoldersNames. Change name FROM='"+zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+"'  TO='"+zfta+"'",zwf,zctf["SPECIAL_CASE"]);zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=zfta;zfsx[zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["accountId"]]=zfta;}
}}else{if(zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]==zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]){var zftb=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDERNAME_PROP]?zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDERNAME_PROP]:(zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDER_PROP]?zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDER_PROP]:this.zfsb);var zftc=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDERNAME_PROP]?zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDERNAME_PROP]:(zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDER_PROP]?zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.SENDER_PROP]:this.zfsb);if(zftb!=zftc){var zftd=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]+" ("+zftb+")";zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=zftd;var zfte=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]+" ("+zftc+")";zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=zfte;zcte("Repository.checkDuplicateFoldersNames. #1.1# Change name FROM='"+zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+"'  TO='"+zfte+"'",zwf,zctf["SPECIAL_CASE"]);zcte("Repository.checkDuplicateFoldersNames. #2.1# Change name FROM='"+zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+"'  TO='"+zftd+"'",zwf,zctf["SPECIAL_CASE"]);zfsx[zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["accountId"]]=zfte;zfsx[zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["accountId"]]=zftd;}
else{var zftd=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]+" ("+zftb+")["+zfsw+"]";zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=zftd;zfsw++;var zfte=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]+" ("+zftb+")["+zfsw+"]";zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=zfte;zcte("Repository.checkDuplicateFoldersNames. #1.2# Change name FROM='"+zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+"'  TO='"+zfte+"'",zwf,zctf["SPECIAL_CASE"]);zcte("Repository.checkDuplicateFoldersNames. #2.2# Change name FROM='"+zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+"'  TO='"+zftd+"'",zwf,zctf["SPECIAL_CASE"]);zfsx[zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["accountId"]]=zfte;zfsx[zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["accountId"]]=zftd;}
}}}else{if(zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){if(zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]==zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]){var zfsz=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP];var sender=zfsz[RfapiJS.SENDERNAME_PROP]?zfsz[RfapiJS.SENDERNAME_PROP]:(zfsz[RfapiJS.SENDER_PROP]?zfsz[RfapiJS.SENDER_PROP]:this.zfsb);var zfta=zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+" ("+sender+")"
zcte("Repository.checkDuplicateFoldersNames.  #3.1# Change name FROM='"+zfsy[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]+"'  TO='"+zfta+"'",zwf,zctf["SPECIAL_CASE"]);zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]=zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=zfta;zfsx[zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["accountId"]]=zfta;}
}}}return zfsx;};zfrx.prototype.zfsf=function(zfsd,zasi){zcte("Repository.resetAccountData ->  accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);var zfir=this.zfrz[zfsd];if(zfir){delete this.zfrz[zfsd][zasi];}
var zfst=this.zfsq()[RfapiJS.ITEM_CHILDS_PROP];if(!zfst){return;}
for(var zcw=0;zcw<zfst.length;zcw++){var zgk=zfst[zcw];var zfsv=zgk[RfapiJS.ITEM_INFO_PROP];if(zfsd==this.zfsb){if(zfsv[RfapiJS.ITEM_SHARED_PROP]){continue;}
zfst.splice(zcw,1);zcw--;}else{if(!zfsv[RfapiJS.ITEM_SHARED_PROP]||(zfsd!=zfsv[RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP])){continue;}
delete zgk[RfapiJS.ITEM_CHILDS_PROP];}}return;};zfrx.prototype.zftf=function(zftg,zfth){var zfsg=[];this.zfry=zftg;if(!this.zfry.length){for(var zfti in this.zfrz){if(zfti==this.zfsb){continue;}
delete this.zfrz[zfti];}if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP]){for(var zcds=0;zcds<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zcds++){if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zcds][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){this.zfsa[RfapiJS.ITEM_CHILDS_PROP].splice(zcds,1);zcds--;}
}}return zfsg;}try{for(var zcw=0;zcw<this.zfry.length;zcw++){var zfir=this.zfry[zcw];var zfsd=zfir[RfapiJS.ACCOUNT_ID_PROP];var zftj=zfir["accepted"];var sender=zfir["sender"];var zftk=zfir["senderName"];var zdbd=zfir["disabled"];if((typeof zftj==zfhx)||(zftj==false)){zcte("Repository.setSharedAccounts. Not accepted account yet. accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);continue;}
if((typeof zdbd!=zfhx)&&(zdbd==true)){zcte("Repository.setSharedAccounts. DISABLED. accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);continue;}
var zftl=zfir["name"];if(!zftl){zcte("Repository.setSharedAccounts. displayName is empty. accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);continue;}
var zcnz=zfir["accountInfo"];if(!zcnz){zcte("Repository.setSharedAccounts. accountInfo is empty. accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);continue;}
var zftm=zcnz["name"];if(!zftm){zcte("Repository.setSharedAccounts. accountInfo[name] is empty. accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);continue;}
zcte("Repository.setSharedAccounts. displayName='"+zftl+"'  accountInfoName='"+zftm+"'",zwf,zctf["SPECIAL_CASE"]);if(zftl!=zftm){var zftn=zftk?zftk:(sender?sender:this.zfsb);var zfto=zftl.indexOf(zftm);if(zfto!=0){if(zftl.substr(zftl.length-1,1)=="]"&&zftl.substr(zftl.length-3,1)=="["&&zftl.substr(zftl.length-4,1)==")"){zfsg[zfsd]=zftm;zfir["name"]=zftm;}
continue;}if(zftl.substr(zftm.length,1)==" "&&zftl.substr(zftm.length+1,1)=="("){zfsg[zfsd]=zftm;zfir["name"]=zftm;}
}}}catch(zdn){zwe("Repository.setSharedAccounts. Error, while getting diff names for ='"+zfsd+"' displayName='"+zftl+"' accountInfoName='"+zftm+"'",zwf);}
for(var zcw=0;zcw<this.zfry.length;zcw++){var zftp=this.zfry[zcw];var zftj=zftp["accepted"];var zdbd=zftp["disabled"];if(!zfth){var zfsd=zftp[RfapiJS.ACCOUNT_ID_PROP];if((typeof zftj==zfhx)||(zftj==false)){continue;}
if((typeof zdbd!=zfhx)&&(zdbd==true)){zcte("Repository.setSharedAccounts. DISABLED. accId='"+zfsd+"'",zwf,zctf["SPECIAL_CASE"]);var zftq=-1;if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP]){for(var zftr=0;zftr<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zftr++){if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zftr][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]&&this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zftr][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP]==zfsd){zftq=zftr;break;}
}}if(zftq!=-1){this.zfsa[RfapiJS.ITEM_CHILDS_PROP].splice(zftq,1);}
continue;}var zfts=this.zfrz[zfsd];if(!zfts){this.zfrz[zfsd]={}
;}if(!this.zfsa[RfapiJS.ITEM_INFO_PROP]){this.zfsj();}
var zftt=this.zftu(zfsd,true);var zftv=-1;for(var zenn=0;zenn<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zenn++){if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zenn][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]&&this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zenn][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP]==zfsd){zftv=zenn;break;}
}var zftw=undefined;if(zftv!=-1){this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zftv][RfapiJS.ITEM_INFO_PROP]=zftt[RfapiJS.ITEM_INFO_PROP];var zftx=this.zfsa[RfapiJS.ITEM_CHILDS_PROP].splice(zftv,1);if(zftx&&zftx.length){zftw=zftx[0];}
if(zftw){var zfsk=this.zfsl(zftw);for(var zdgk in zfsk){zfsg[zdgk]=zfsk[zdgk];}
this.zfsa[RfapiJS.ITEM_CHILDS_PROP].splice(zftv,0,zftw);}
}else{var zfsk=this.zfsl(zftt);for(var zdgk in zfsk){zfsg[zdgk]=zfsk[zdgk];}
zawd.zfsm(zftt,this.zfsa[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);}
}else{var zfsd=zftp[RfapiJS.ACCOUNT_ID_PROP];var zfty=true;if((typeof zftj==zfhx)||(zftj==false)){zfty=false;}
var zfts=this.zfrz[zfsd];if(zfts&&!zfty){delete this.zfrz[zfsd];}
else if(!zfts&&zfty){this.zfrz[zfsd]={};}if(!this.zfsa[RfapiJS.ITEM_INFO_PROP]){this.zfsj();}
var zep=-1;for(var zenm=0;zenm<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zenm++){if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zenm][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]&&this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zenm][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP]==zfsd){zep=zenm;break;}
}if(zep!=-1&&!zfty){this.zfsa[RfapiJS.ITEM_CHILDS_PROP].splice(zep,1);}
else if(zep==-1&&zfty){var zftt=this.zftu(zfsd,true);var zfsk=this.zfsl(zftt);for(var zdgl in zfsk){zfsg[zdgl]=zfsk[zdgl];}
zawd.zfsm(zftt,this.zfsa[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);}
}}return zfsg;};zfrx.prototype.zfsj=function(){this.zfsa[RfapiJS.ITEM_INFO_PROP]={}
;this.zfsa[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_ISFOLDER_PROP]=true;this.zfsa[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=RfapiJS.ROOT_NODE;this.zfsa[RfapiJS.ITEM_CHILDS_PROP]=[];}
;zfrx.prototype.zftz=function(){var zftg=[];if(!this.zfry){return zftg;}
for(var zcw=0;zcw<this.zfry.length;zcw++){var zftp=this.zfry[zcw];var zftj=zftp["accepted"];if((typeof zftj==zfhx)||(zftj==false)){continue;}
zftg.push(zftp);}return zftg;};zfrx.prototype.zfua=function(zfsd,name){for(var zcw=0;zcw<this.zfry.length;zcw++){if(this.zfry[zcw][RfapiJS.ACCOUNT_ID_PROP]==zfsd){this.zfry[zcw][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=name;this.zfry[zcw][RfapiJS.NAME_PROP]=name;break;}
}if(!this.zfsa[RfapiJS.ITEM_CHILDS_PROP]){return;}
for(var zcw=0;zcw<this.zfsa[RfapiJS.ITEM_CHILDS_PROP].length;zcw++){if(!this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){continue;}
if(this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP]!=zfsd){continue;}
this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=name;this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP][RfapiJS.NAME_PROP]=name;this.zfsa[RfapiJS.ITEM_CHILDS_PROP][zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.NAME_PROP]=name;break;}
};zfrx.prototype.zfub=function(name){for(var zcw=0;zcw<this.zfry.length;zcw++){var zftp=this.zfry[zcw];if(zftp[RfapiJS.NAME_PROP]==name){return zftp[RfapiJS.ACCOUNT_ID_PROP];}
}return"";};zfrx.prototype.zftu=function(zbjy,zfuc){for(var zcw=0;zcw<this.zfry.length;zcw++){var zftp=this.zfry[zcw];if(zftp[RfapiJS.ACCOUNT_ID_PROP]==zbjy){var zfir={}
;zfir[RfapiJS.ITEM_INFO_PROP]={};zfir[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_ISFOLDER_PROP]=true;zfir[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_CRETIME_PROP]=0;zfir[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_MODTIME_PROP]=0;zfir[RfapiJS.ITEM_INFO_PROP][zfqp]=0;zfir[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]={}
;zfir[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zftp[RfapiJS.NAME_PROP];for(var zfud in zftp){zfir[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][zfud]=zftp[zfud];}
return zfir;}}return null;};zfrx.prototype.zfue=function(){var zfuf=null;var zfug=this.zfse(zfht["USER_DATA"],this.zfsb);if(!zfug){zwe("Repository.getPrivateKey: Cannot get OFS root folder for user='"+this.zfsb+"'",zwf);return zfuf;}
var zfsr=zfug[RfapiJS.ITEM_CHILDS_PROP];if(!zfsr){zwe("Repository.getPrivateKey: Cannot get childs of the root folder for user='"+this.zfsb+"'",zwf);return zfuf;}
for(var zcw=0;zcw<zfsr.length;zcw++){if(zfsr[zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=="private-key.pem"){zfuf=zfsr[zcw][RfapiJS.ITEM_BODY_PROP];break;}
}return zfuf;};zfrx.prototype.zfuh=function(zfui){var zfuj=Math.round(new Date()/1000);var zfsr=this.zfse(zfht["USER_DATA"],this.zfsb)[RfapiJS.ITEM_CHILDS_PROP];var key={}
;key[RfapiJS.ITEM_BODY_PROP]=zfui;key[RfapiJS.ITEM_INFO_PROP]={}
;key[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_CRETIME_PROP]=zfuj;key[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_MODTIME_PROP]=zfuj;key[RfapiJS.ITEM_INFO_PROP][zfqp]=zfui.length;key[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]="private-key.pem";zfsr.unshift(key);return;}
;zfrx.prototype.zfuk=function(zatm,zful,zfjt,zfju){var zfum=this.zfun(this.zfsb);if(!zfum){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+" mru.rfo",undefined,undefined,"NotFound"));}
return false;}var zfuo=JSON.parse(zfum["b"]);if(!zfuo){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,"Cannot parse mru.rfo",undefined,undefined,"NotFound"));}
return false;}if(zatm==zfpz["usiRecentlyUsedList"]){this.zfup(zfuo,"usageCounters",zful);this.zfup(zfuo,"recentlyUsed",zful);zfum["b"]=JSON.stringify(zfuo);}
else if(zatm==zfpz["usiFavouritesList"]){zfuo["favorites5"]["timestamp"]=this.getTime();var zcks=-1;for(var zcw=0;zcw<zfuo["favorites5"]["list"].length;zcw++){var item=zatm[zcw];var path=item;if(path==zful){zcks=zcw;break;}
}if(zcks==-1){if(zfuo["favorites5"]["list"].length==5){zfuo["favorites5"]["list"].pop();}
zfuo["favorites5"]["list"].push(zful);}zfum["b"]=JSON.stringify(zfuo);}
return true;};zfrx.prototype.zfup=function(zfuo,zfuq,zful){if(!zfuo[zfuq]){zfuo[zfuq]=new Object();zfuo[zfuq]["list"]=[];}
var zatm=zfuo[zfuq]["list"];var zcks=-1;for(var zcw=0;zcw<zatm.length;zcw++){var item=zatm[zcw];var path=typeof item["path"]==zfhx?item:item["path"];if(path==zful){zcks=zcw;break;}
}if(zcks==-1){var zfur={};zfur["path"]=zful;zfur["timestamp"]=this.getTime();if(zfuq=="usageCounters"){zfur["usageCounter"]=1;}
zatm.push(zfur);}else{if(zfuq=="usageCounters"){zatm[zcks]["usageCounter"]++;}
zatm[zcks]["timestamp"]=this.getTime();}};zfrx.prototype.zfun=function(zfsd){var zfus=null;var zfut=this.zfrz[zfsd][zfht["APP_DATA"]];var zfsr=zfut[RfapiJS.ITEM_CHILDS_PROP];for(var zcw=0;zcw<zfsr.length;zcw++){if(zfsr[zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=="mru.rfo"){zfus=zfsr[zcw];break;}
}return zfus;};zfrx.prototype[zfrk]=function(zfuu,zfjt,zfju){var zatm=zfuu[zfqu]["list"];var zaex=zfuu[zfqu]["type"];var zfum=this.zfun(this.zfsb);if(!zfum){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+" mru.rfo",undefined,undefined,"NotFound"));}
return;}var zfuo=JSON.parse(zfum["b"]);if(!zfuo){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,"Cannot parse mru.rfo",undefined,undefined,"NotFound"));}
return;}var zss=[];if(zatm==zfpz["usiRecentlyUsedList"]){zss=typeof zfuo["recentlyUsed"]!=zfhx?zfuo["recentlyUsed"]:[];}
else if(zatm==zfpz["usiFavouritesList"]){zss=typeof zfuo["favorites5"]!=zfhx?zfuo["favorites5"]:[];}
else if(zatm==zfpz["usiRecentlyViewedList"]){zss=typeof zfuo["recentlyViewed"]!=zfhx?zfuo["recentlyViewed"]:[];}
else if(zatm==zfpz["usiMostPopularList"]){zss=typeof zfuo["usageCounters"]!=zfhx?zfuo["usageCounters"]:[];}
var zgv=[];if(zss["list"]){for(var zcw=0;zcw<zss["list"].length;zcw++){var item=zss["list"][zcw];var path=typeof item["path"]==zfhx?item:item["path"];var zfcl=path.substr(path.lastIndexOf("."));var zcda=zawd.zfuv(zfcl);if(!zaex||parseInt(zaex)==zcda){zgv.push(item);}
}}if(typeof(zfjt)!=zfhx){zfjt(zgv,false,[]);}return;}
;zfrx.prototype[zfrm]=function(zfuu,zfjt,zfju){var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(path,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+path));}
return;}var zfcl=path.substr(path.lastIndexOf("."));var zcda=zawd.zfuv(zfcl);var item=this.zfux(path,zcda,zfju);if(!item){return false;}
var zfuy=((typeof item[RfapiJS.ITEM_ENCODED_PROP]!=zfhx)&&(item[RfapiJS.ITEM_ENCODED_PROP]==true))?true:false;var body=item[RfapiJS.ITEM_BODY_PROP];if(zfuy){body=this.zfuz(path,body,true);}
if(typeof(zfjt)!=zfhx){zfjt(body,false,[]);}return true;}
;zfrx.prototype[zfrn]=function(zfuu,zfjt,zfju){var self=this;var zfva=zfuu[zfqu]["search"];var zfuu={"request":{"function":"search","path":"","type":zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP],"parts":zfuu[zfqu]["parts"],"deep":zfuu[zfqu]["deep"]
}
};self[zfrw](zfuu,function(zfvb){var zgv=[];for(var zcw=0;zcw<zfvb.length;zcw++){var item=zfvb[zcw];var zans=item[RfapiJS.ITEMINFO_PATH_PROP];zans=zans.toLowerCase();var zfvc=zans.substr(zans.lastIndexOf("/")+1);if(item[RfapiJS.ITEMINFO_TYPE_PROP]!=ztk["RfItemType_Folder"]){zfvc=zfvc.substr(0,zfvc.lastIndexOf("."));}
if(((zfva.length>2)&&(zfvc.lastIndexOf(zfva)==-1))){continue;}
if(zfva.length<=2){if(zfvc.lastIndexOf(zfva)==-1){continue;}
if((zfvc.indexOf(zfva)!=0)&&zawd.zcre(zfvc,zfva,' ')==false&&zawd.zcre(zfvc,zfva,'.')==false&&zawd.zcre(zfvc,zfva,'-')==false&&zawd.zcre(zfvc,zfva,'_')==false){continue;}
}var zfir=self.zfvd(item["path"],item["type"]);item["isShared"]=zfir["isShared"];item["readOnly"]=zfir["readOnly"];item["showPasswords"]=zfir["showPasswords"];item["disabled"]=zfir["disabled"];item["isAdmin"]=zfir["isAdmin"];item["isManager"]=zfir["isManager"];item["licenseExpired"]=zfir["licenseExpired"];item["isAllowedIP"]=zfir["isAllowedIP"];zgv.push(item);}
if(typeof(zfjt)!=zfhx){zfjt(zgv,false,[]);}},zfju);}
;zfrx.prototype[zfrj]=function(zfuu,zfjt,zfju){var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(path,false)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+path));}
return;}var zfb=this.zfve(this.zfsq(),path,zfrg);if(!zfb){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc+"'"+path+"'",undefined,undefined,"NotFound"));}
return;}var zfr=typeof(zfuu[zfqu][zfqv])==zfhx?zfpx["enNothing"]:zfuu[zfqu][zfqv];zfr=parseInt(zfr);var zss=[];var zfvf=0;var zfvg=0;var zfvh=0;var zgv={}
;zgv[RfapiJS.ITEMINFO_SIZE_PROP]=zfvf;zgv["count"]=0;if(!zfb[RfapiJS.ITEM_CHILDS_PROP]){if(typeof(zfjt)!=zfhx){zfjt(zgv,false,[]);}
return;}var zfvi={};zfvi[RfapiJS.ITEM_INFO_PROP]=zfb[RfapiJS.ITEM_INFO_PROP];zfvi[RfapiJS.ITEM_CHILDS_PROP]=[];var zfvj=zfuu[zfqu]["bExcludeShared"];if(zfvj){for(var zgg=0;zgg<zfb[RfapiJS.ITEM_CHILDS_PROP].length;zgg++){if(zfb[RfapiJS.ITEM_CHILDS_PROP][zgg][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){continue;}
zfvi[RfapiJS.ITEM_CHILDS_PROP].push(zfb[RfapiJS.ITEM_CHILDS_PROP][zgg]);}
}else{zfvi[RfapiJS.ITEM_CHILDS_PROP]=zfb[RfapiJS.ITEM_CHILDS_PROP];}
var zbxk=zfvi[RfapiJS.ITEM_CHILDS_PROP].length;if(zbxk){var zcvc=typeof(zfuu[zfqu][zfqt])==zfhx?false:zfuu[zfqu][zfqt];var zbjl=typeof(zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP])==zfhx?"":zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];if(zbjl!=""){if(typeof(zbjl)=="object"){var zfvk=zbjl;}
else{var zcqi=JSON.parse(zbjl);var zfvk=(typeof(zcqi)=="number")?[zcqi]:zcqi;}
}else{var zfvk=zfqi;}this.zvq(path,zfvi,zfvk,zcvc,zfr,false,zss,true,false);zgv["count"]=zss.length;for(var zcw=0;zcw<zss.length;zcw++){var zfvl=typeof zss[zcw][RfapiJS.ITEMINFO_SIZE_PROP]==zfhx?0:zss[zcw][RfapiJS.ITEMINFO_SIZE_PROP];zfvf+=zfvl;var zfby=typeof zss[zcw][zfvm]==zfhx?false:zss[zcw][zfvm];zfvg+=zfby==true?1:0;zfvh+=zfby==true?0:1;}
zgv[RfapiJS.ITEMINFO_SIZE_PROP]=zfvf;}if(zfr&zfpx["enFlags"]){zgv[zfvm]=zfvg;zgv["unprotected"]=zfvh;}
if(typeof(zfjt)!=zfhx){zfjt(zgv,false,[]);}return;}
;zfrx.prototype[zfrh]=function(zfuu,zfjt,zfju){var path=zfrg;var zfb=this.zfve(this.zfsq(),path,zfrg);if(!zfb){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"NotFound"));}
return;}var zfvn=zfuu[zfqu][zfqs];var zcvc=true;var zfvo=false;var zbjl=typeof(zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP])==zfhx?"":zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];var zfvk=null;if(zbjl==""){zfvk=[ztk["RfItemType_Login"],ztk["RfItemType_Bookmark"]];}
else{if(typeof zbjl=="object"){zfvk=zbjl;}else{var zcqi=JSON.parse(zbjl);zfvk=(typeof(zcqi)=="number")?[zcqi]:zcqi;}
}var zfr=4;var zss=[];this.zvq(path,zfb,zfvk,zcvc,zfr,zfvo,zss,false,false);var zgv=[];for(var zcw=0;zcw<zss.length;zcw++){var item=zss[zcw];var zfvp=item[zfqx];if(zfvp.startsWith(zfvn)){var zfvq=new Object();zfvq[RfapiJS.ITEMINFO_TYPE_PROP]=item[RfapiJS.ITEMINFO_TYPE_PROP];zfvq[RfapiJS.ITEMINFO_PATH_PROP]=item[RfapiJS.ITEMINFO_PATH_PROP];if(zfvp==zfvn){zfvq[zfra]=zfpy["RF_MATCH_TYPE_URL_EXACT"];}
else{zfvq[zfra]=zfpy["RF_MATCH_TYPE_DOMAIN"];}zfvq[zfrc]=true;zgv.push(zfvq);}
}if(typeof(zfjt)!=zfhx){zfjt(zgv,false,[]);}return;}
;zfrx.prototype[zfri]=function(zfuu,zfjt,zfju){var path=zfrg;var zfb=this.zfve(this.zfsq(),path,zfrg);if(!zfb){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"NotFound"));}
return;}var zfvn=zfuu[zfqu][zfqs];var zcvc=true;var zfvo=false;var zbjl=typeof(zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP])==zfhx?"":zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];var zfvk=null;if(zbjl==""){zfvk=[ztk["RfItemType_Login"]];}
else{if(typeof zbjl=="object"){zfvk=zbjl;}else{var zcqi=JSON.parse(zbjl);zfvk=(typeof(zcqi)=="number")?[zcqi]:zcqi;}
}var zfr=4;var zss=[];this.zvq(path,zfb,zfvk,zcvc,zfr,zfvo,zss,false,false);var zgv=[];var zfvn=zfvn.toLowerCase();var zfvr=zty(zfvn);if(zfvr){for(var zcw=0;zcw<zss.length;zcw++){try{var item=zss[zcw];var zfvs=[item[zfqx],item[zfqw]];for(var zfvt=0;zfvt<2;zfvt++){var zfvp=zfvs[zfvt];if(zfvp){zfvp=zfvp.toLowerCase();zfvp=decodeURIComponent(zfvp);var zfvu=zty(zfvp);if((zfvr==zfvu)||(zfvp.startsWith(zfvn))){var zfvq={}
;zfvq[RfapiJS.ITEMINFO_TYPE_PROP]=item[RfapiJS.ITEMINFO_TYPE_PROP];zfvq[RfapiJS.ITEMINFO_PATH_PROP]=item[RfapiJS.ITEMINFO_PATH_PROP];zgv.push(zfvq);break;}
}}}catch(zdn){zwe("Repository.GetDomainCards. Error, while comparing url's  index ='"+zcw+"'  err="+zdn,zwf);}
}}if(typeof(zfjt)!=zfhx){zfjt({"status":"ok","items":zgv}
,false,[]);}return;};zfrx.prototype["GetItemsCount2"]=function(zfuu,zfkt,zfjt,zfju){var zvd;var zfsr=zfkt["c"];if(!zfsr){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"There are no childs items"));}
return;}for(var zcw=0;zcw<zfsr.length;zcw++){if(zfsr[zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==RfapiJS.ROOT_NODE){zvd=zfsr[zcw];break;}
}if(!zvd){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"There is no root"));}
return;}var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];var zfb=this.zfve(zvd,path,zfrg);if(!zfb){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"NotFound"));}
return;}var zgv={"loginsCount":0,"identitiesCount":0,"contactsCount":0,"safenotesCount":0,"bookmarksCount":0,"searchCardsCount":0,"blockingCardsCount":0,"allItemsCount":0}
;var zgh=zfb[RfapiJS.ITEM_CHILDS_PROP];if(!zgh){if(typeof(zfjt)!=zfhx){zfjt(zgv);}
return;}var zbxk=zgh.length;if(zbxk){var zfr=typeof(zfuu[zfqu][zfqv])==zfhx?zfpx["enNothing"]:zfuu[zfqu][zfqv];zfr=parseInt(zfr);var zcvc=typeof(zfuu[zfqu][zfqt])==zfhx?false:zfuu[zfqu][zfqt];var zbjl=typeof(zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP])==zfhx?"":zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];if(zbjl!=""){if(typeof(zbjl)=="object"){var zfvk=zbjl;}
else{var zcqi=JSON.parse(zbjl);var zfvk=(typeof(zcqi)=="number")?[zcqi]:zcqi;}
}else{var zfvk=zfqi;}var zfvv=[];this.zvq(path,zfb,[1,2,3,4,5,6,7],zcvc,zfr,false,zfvv,true,false);zgv["allItemsCount"]=zfvv.length;for(var zcw=0;zcw<zfvk.length;zcw++){var zceq=zfvk[zcw];var zfvv=[];this.zvq(path,zfb,[zceq],zcvc,zfr,false,zfvv,true,false);switch(zceq){case ztk["RfItemType_Login"]:zgv["loginsCount"]=zfvv.length;break;case ztk["RfItemType_Bookmark"]:zgv["bookmarksCount"]=zfvv.length;break;case ztk["RfItemType_SearchCard"]:zgv["searchCardsCount"]=zfvv.length;break;case ztk["RfItemType_BlockingPasscard"]:zgv["blockingCardsCount"]=zfvv.length;break;case ztk["RfItemType_Identity"]:zgv["identitiesCount"]=zfvv.length;break;case ztk["RfItemType_Contact"]:zgv["contactsCount"]=zfvv.length;break;case ztk["RfItemType_Safenote"]:zgv["safenotesCount"]=zfvv.length;break;}
}}if(typeof(zfjt)!=zfhx){zfjt(zgv);}return;};zfrx.prototype["GetItemsList2"]=function(zfuu,zfkt,zfjt,zfju){var zvd;var zfsr=zfkt["c"];if(!zfsr){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"There are no childs items"));}
return;}for(var zcw=0;zcw<zfsr.length;zcw++){if(zfsr[zcw][RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==RfapiJS.ROOT_NODE){zvd=zfsr[zcw];break;}
}if(!zvd){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"There is no root"));}
return;}var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];var zfb=this.zfve(zvd,path,zfrg);if(!zfb){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"NotFound"));}
return;}var zgv=[];var zgh=zfb[RfapiJS.ITEM_CHILDS_PROP];if(!zgh){if(typeof(zfjt)!=zfhx){zfjt(zgv);}
return;}var zbxk=zgh.length;if(zbxk){var zfvo=typeof(zfuu[zfqu][zfqy])==zfhx?false:zfuu[zfqu][zfqy];var zcvc=typeof(zfuu[zfqu][zfqt])==zfhx?false:zfuu[zfqu][zfqt];var zbjl=typeof(zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP])==zfhx?"":zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];var zcve=typeof(zfuu[zfqu]["bBody"])==zfhx?false:zfuu[zfqu]["bBody"];if(zbjl!=""){if(typeof(zbjl)=="object"){var zfvk=zbjl;}
else{var zcqi=JSON.parse(zbjl);var zfvk=(typeof(zcqi)=="number")?[zcqi]:zcqi;}
}else{var zfvk=zfqi;}var zfr=typeof(zfuu[zfqu][zfqv])==zfhx?zfpx["enNothing"]:zfuu[zfqu][zfqv];this.zvq(path,zfb,zfvk,zcvc,zfr,zfvo,zgv,false,zcve);}
if(typeof(zfjt)!=zfhx){zfjt(zgv);}return;};zfrx.prototype[zfrw]=function(zfuu,zfjt,zfju){var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(path,false)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+path));}
return;}var zfb=this.zfve(this.zfsq(),path,zfrg);if(!zfb){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqc,undefined,undefined,"NotFound"));}
return;}var zgv=[];var zgh=zfb[RfapiJS.ITEM_CHILDS_PROP];if(!zgh){if(typeof(zfjt)!=zfhx){zfjt(zgv,false,[]);}
return;}var zbxk=zgh.length;if(zbxk){var zfvo=typeof(zfuu[zfqu][zfqy])==zfhx?false:zfuu[zfqu][zfqy];var zcvc=typeof(zfuu[zfqu][zfqt])==zfhx?false:zfuu[zfqu][zfqt];var zbjl=typeof(zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP])==zfhx?"":zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];var zcve=typeof(zfuu[zfqu]["bBody"])==zfhx?false:zfuu[zfqu]["bBody"];if(zbjl!=""){if(typeof(zbjl)=="object"){var zfvk=zbjl;}
else{var zcqi=JSON.parse(zbjl);var zfvk=(typeof(zcqi)=="number")?[zcqi]:zcqi;}
}else{var zfvk=zfqi;}var zfr=typeof(zfuu[zfqu][zfqv])==zfhx?zfpx["enNothing"]:zfuu[zfqu][zfqv];this.zvq(path,zfb,zfvk,zcvc,zfr,zfvo,zgv,false,zcve);}
if(typeof(zfjt)!=zfhx){zfjt(zgv,false,[]);}return;}
;zfrx.prototype[zfrp]=function(zfuu,zfjt,zfju){var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(path,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+path));}
return;}var zcda=zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];var item=this.zfux(path,zcda,zfju);if(!item){return false;}
var zfr=zfpx["enAll"];if(typeof(zfjt)!=zfhx){var zfvw=this.zfvx(item,path,zcda,zfr,true,false);zfjt(zfvw,false,[]);}
return true;};zfrx.prototype[zfrv]=function(zfuu,zfjt,zfju){var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];path=path.trim();if(!this.zfuw(path,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+path));}
return;}var zcda=zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];zcda=parseInt(zcda);if((zcda<ztk["RfItemType_Login"])||(zcda>ztk["RfItemType_Safenote"])){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],"Wrong item type:"+zcda));}
return false;}var zfir=this.zfvd(path,zcda);if(!zfir){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],"Cannot determine account name."));}
return false;}var zfvy=zfir[RfapiJS.NAME_PROP];var zfvz=false;var zfwa=this.getTime();var item=this.zfux(path,zcda,undefined,true);if(!item){zfvz=true;var zdwx=path.substr(0,path.lastIndexOf("/")+1);if(zdwx.endsWith("/")){zdwx=zdwx.substr(0,zdwx.length-1);}
if(zdwx=="/"){zdwx=zfrg;}var zfwb=this.zfux(zdwx,ztk["RfItemType_Folder"],zfju);if(!zfwb){return false;}
item=new Object();item[RfapiJS.ITEM_INFO_PROP]=new Object();item[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_CRETIME_PROP]=zfwa;var zya=path.substr(path.lastIndexOf("/")+1);item[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zya;var zwr=new Object();var zfwc=JSON.stringify(zwr);item[RfapiJS.ITEM_BODY_PROP]=zfwc;item[RfapiJS.ITEM_INFO_PROP][zfqp]=zfwc.length;}
if(item&&(typeof(item[RfapiJS.ITEM_CHILDS_PROP])!=zfhx)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],"Folder with the same name already exists"));}
return false;}var data=zfuu[zfqu]["data"];item[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_MODTIME_PROP]=zfwa;var zfuy=((typeof item[RfapiJS.ITEM_ENCODED_PROP]!=zfhx)&&(item[RfapiJS.ITEM_ENCODED_PROP]==true))?true:false;var body=item[RfapiJS.ITEM_BODY_PROP];if(zfuy){body=this.zfuz(path,body,true);}
var zfwd=typeof body==zfhx?{}:JSON.parse(body);if(typeof data[zfqr]!=zfhx){zfwd[zfqr]=true;zfwd["pwd"]=data["pwd"];}
else{delete zfwd[zfqr];delete zfwd["pwd"];}if(zcda==ztk["RfItemType_Login"]){zfwd[RfapiJS.ITEM_NOTE_PROP]=data[RfapiJS.ITEM_NOTE_PROP];zfwd[RfapiJS.ITEM_GOTOURL_PROP]=data[RfapiJS.ITEM_GOTOURL_PROP];zfwd[RfapiJS.ITEM_MATCHURL_PROP]=data[RfapiJS.ITEM_MATCHURL_PROP];zfwd[RfapiJS.ITEMDATA_FIELDS_PROP]=data[RfapiJS.ITEMDATA_FIELDS_PROP];}
else if(zcda==ztk["RfItemType_Bookmark"]){zfwd[RfapiJS.ITEM_NOTE_PROP]=data[RfapiJS.ITEM_NOTE_PROP];zfwd[RfapiJS.ITEM_GOTOURL_PROP]=data[RfapiJS.ITEM_GOTOURL_PROP];}
else if(zcda==ztk["RfItemType_SearchCard"]){zfwd[RfapiJS.ITEM_NOTE_PROP]=data[RfapiJS.ITEM_NOTE_PROP];zfwd[RfapiJS.ITEM_GOTOURL_PROP]=data[RfapiJS.ITEM_GOTOURL_PROP];zfwd[RfapiJS.ITEM_MATCHURL_PROP]=data[RfapiJS.ITEM_MATCHURL_PROP];zfwd[RfapiJS.ITEMDATA_FIELDS_PROP]=data[RfapiJS.ITEMDATA_FIELDS_PROP];}
else if(zcda==ztk["RfItemType_BlockingPasscard"]){zfwd[RfapiJS.ITEM_NOTE_PROP]=data[RfapiJS.ITEM_NOTE_PROP];zfwd[RfapiJS.ITEM_MATCHURL_PROP]=data[RfapiJS.ITEM_MATCHURL_PROP];zfwd[RfapiJS.ITEMDATA_BLOCK_PROP]=data[RfapiJS.ITEMDATA_BLOCK_PROP];}
else if(zcda==ztk["RfItemType_Safenote"]){zfwd[RfapiJS.ITEM_NOTE_PROP]=data[RfapiJS.ITEM_NOTE_PROP];}
else if(zcda==ztk["RfItemType_Contact"]||zcda==ztk["RfItemType_Identity"]){zfwd[RfapiJS.ID_OPTIONS_PROP]=data[RfapiJS.ID_OPTIONS_PROP];zfwd[RfapiJS.ID_GROUPS_PROP]=data[RfapiJS.ID_GROUPS_PROP];}
var zfwe=JSON.stringify(zfwd);if(zfuy){zfwe=this.zfuz(path,zfwe,false);}
item[RfapiJS.ITEM_BODY_PROP]=zfwe;item[RfapiJS.ITEM_INFO_PROP][zfqp]=zfwe.length;if(zfvz){if(!zfwb[RfapiJS.ITEM_CHILDS_PROP]){zfwb[RfapiJS.ITEM_CHILDS_PROP]=[];}
zfwb[RfapiJS.ITEM_CHILDS_PROP].push(item);}var zftg=[];var zfsd=zfir["id"];this.zfss(zfsd);zftg.push(zfsd);if(typeof(zfjt)!=zfhx){zfjt(zcue,true,zftg);}
return true;};zfrx.prototype[zfro]=function(zfuu,zfjt,zfju){var zcda=zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];if(!zcda){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],"Wrong item type:"+zcda));}
return false;}if(((zcda<ztk["RfItemType_Login"])||(zcda>ztk["RfItemType_Safenote"]))){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],"Wrong item type:"+zcda));}
return false;}if(zcda==ztk["RfItemType_BlockingPasscard"]){var zcsg=new Object();zcsg[RfapiJS.ITEM_NOTE_PROP]="";zcsg[RfapiJS.ITEM_MATCHURL_PROP]="";zcsg[RfapiJS.ITEMDATA_BLOCK_PROP]=0;if(typeof(zfjt)!=zfhx){zfjt(zcsg);}
return true;}else if(zcda==ztk["RfItemType_SearchCard"]){var zcsg=new Object();zcsg[RfapiJS.ITEM_NOTE_PROP]="";zcsg[RfapiJS.ITEM_GOTOURL_PROP]="";zcsg[RfapiJS.ITEM_MATCHURL_PROP]="";zcsg[RfapiJS.ITEMDATA_FIELDS_PROP]=[];if(typeof(zfjt)!=zfhx){zfjt(zcsg);}
return true;}else if(zcda==ztk["RfItemType_Safenote"]){var zcsg=new Object();zcsg[RfapiJS.ITEM_NOTE_PROP]="";if(typeof(zfjt)!=zfhx){zfjt(zcsg);}
return true;}else if(zcda==ztk["RfItemType_Bookmark"]){var zcsg=new Object();zcsg[RfapiJS.ITEM_NOTE_PROP]="";zcsg[RfapiJS.ITEM_GOTOURL_PROP]="";if(typeof(zfjt)!=zfhx){zfjt(zcsg);}
return true;}else if(zcda==ztk["RfItemType_Login"]){var zcsg=new Object();zcsg[RfapiJS.ITEM_NOTE_PROP]="";zcsg[RfapiJS.ITEM_GOTOURL_PROP]="";zcsg[RfapiJS.ITEM_MATCHURL_PROP]="";zcsg[RfapiJS.ITEMDATA_FIELDS_PROP]=[];if(typeof(zfjt)!=zfhx){zfjt(zcsg);}
return true;}else if(zcda==ztk["RfItemType_Contact"]||zcda==ztk["RfItemType_Identity"]){var zcsg=new Object();zcsg[RfapiJS.ID_OPTIONS_PROP]={}
;zcsg[RfapiJS.ID_OPTIONS_PROP][zfql]=zcda==ztk["RfItemType_Contact"]?"":"+";if((zcda==ztk["RfItemType_Identity"])&&(typeof zfuu[zfqu][zfre]!=zfhx)&&(zfuu[zfqu][zfre]==true)){zcsg[RfapiJS.ID_OPTIONS_PROP][zfqm]="+";}
if(typeof zfuu[zfqu][zfrf]!=zfhx){var zfwf=parseInt(zfuu[zfqu][zfrf]);if(zfwf==1||zfwf==2){zcsg[RfapiJS.ID_OPTIONS_PROP][zfqn]=zfwf;}
}var zdiw;if(typeof zfuu[zfqu]["country"]!=zfhx){zdiw=zfuu[zfqu]["country"];if(!zze(zfqa,zdiw)){zdiw="United States";}
}else{zdiw="United States";}zcsg[RfapiJS.ID_OPTIONS_PROP]["World Regions"]=zdiw;var zfwg={}
;zfwg["World Regions"]=zdiw;zfwg[zfql]=zcsg[RfapiJS.ID_OPTIONS_PROP][zfql];if((zcda==ztk["RfItemType_Identity"])&&(typeof zcsg[RfapiJS.ID_OPTIONS_PROP][zfqm]!=zfhx)){zfwg[zfqm]="+";}
zcsg[RfapiJS.ID_GROUPS_PROP]=[];var zwt=new RfapiJS.CIdentity(zfwg);var zfwh=zwt.zchx();var zfwi=zfwh.zchz;for(var zcw=0;zcw<zfwi.length;zcw++){var zfwj=zfwi[zcw];var zxo=new Object();zxo[RfapiJS.ITEM_NAME_PROP]=zfwj[zfqo];zxo[RfapiJS.ID_INSTANCES_PROP]=[];var zfwk=new Object();zfwk[RfapiJS.ITEM_NAME_PROP]="Main";zfwk[RfapiJS.ITEM_ISDEFAULT_PROP]=true;zfwk[RfapiJS.ITEMDATA_FIELDS_PROP]=[];for(var zbnr=0;zbnr<zfwj[zfqk].length;++zbnr){var zclf=zfwj[zfqk][zbnr];var zuy=zfwh.zcjd(zclf);if(!zuy){continue;}
var zcje=zuy.zcjf;if(zfwj[zfqo]=="Location"&&zclf=="Country"){}
else if(zcje.zcjh()){continue;}var zxy=new Object();zxy[RfapiJS.ITEM_NAME_PROP]=zclf;if(zcje.zcjy==1){zxy[RfapiJS.ID_OPTIONS_PROP]=[];for(var zgg=0;zgg<zcje.zclq.length;zgg++){zxy[RfapiJS.ID_OPTIONS_PROP].push(zcje.zclq[zgg].zclr);}
}var zcjo=zuy.zawl(zfwh,"Main");zxy[RfapiJS.FIELD_VALUE_PROP]=zcjo;zfwk[RfapiJS.ITEMDATA_FIELDS_PROP].push(zxy);}
zxo[RfapiJS.ID_INSTANCES_PROP].push(zfwk);zcsg[RfapiJS.ID_GROUPS_PROP].push(zxo);}
if(typeof(zfjt)!=zfhx){zfjt(zcsg);}return true;}return;}
;zfrx.prototype[zfrl]=function(zfuu,zfjt,zfju){var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(path,false)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+path));}
return;}var zbvu=path.substring(path.lastIndexOf("/")+1);var zcda=zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];var item=null;if((typeof zcda==zfhx)||zcda==""){var zcks=zbvu.lastIndexOf(".");item=this.zfux(path,ztk["RfItemType_Folder"]);if(zcks==-1){if(!item){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+path+" Type:"+ztk["RfItemType_Folder"],undefined,undefined,"NotFound"));}
return false;}zcda=ztk["RfItemType_Folder"];}else{if(!item){var zfcl=zbvu.substr(zcks);zcda=zawd.zfuv(zfcl);item=this.zfux(path,zcda,zfju);if(!item){return false;}
}else{zcda=ztk["RfItemType_Folder"];}}}else{item=this.zfux(path,zcda,zfju);if(!item){return false;}
}var zfr=typeof(zfuu[zfqu][zfqv])==zfhx?zfpx["enNothing"]:zfuu[zfqu][zfqv];var zfvo=typeof(zfuu[zfqu]["iconMime"])==zfhx?false:((zfuu[zfqu]["iconMime"]=="")?false:zfuu[zfqu]["iconMime"]);if(typeof(zfjt)!=zfhx){var zfvw=this.zfvx(item,path,zcda,zfr,false,zfvo);zfjt(zfvw,false,[]);}
return true;};zfrx.prototype[zfrt]=function(zfuu,zfjt,zfju){this[zfru](zfuu,zfjt,zfju,true);}
;zfrx.prototype[zfru]=function(zfuu,zfjt,zfju,zfwl){var zfwm=zfuu[zfqu]["from"][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(zfwm,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+zfwm));}
return;}var zfwn=zfuu[zfqu]["from"][RfapiJS.ITEMINFO_TYPE_PROP];if(typeof(zfwn)==zfhx){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],zfqh+zfwn));}
return;}var zfwo=this.zfvd(zfwm,zfwn);if(!zfwo){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],"Cannot determine account name[from]."));}
return false;}var zfwp=zfwo[RfapiJS.NAME_PROP];var zfwq=zfuu[zfqu]["to"][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(zfwq,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+zfwq));}
return;}var zfwr=zfuu[zfqu]["to"][RfapiJS.ITEMINFO_TYPE_PROP];if(typeof(zfwr)==zfhx){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],zfqh+zfwr));}
return;}var zfws=this.zfvd(zfwq,zfwr);if(!zfws){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],"Cannot determine account name[to]."));}
return false;}var zfwt=zfws[RfapiJS.NAME_PROP];if(zfwn!=zfwr){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],"Wrong types: From="+zfwn+" To:"+zfwr));}
return;}if((zfwn==ztk["RfItemType_Folder"])&&(zfwm==zfwq)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],"Cannot move/copy folder to itself Type="+zfwn+" Path:'"+zfwm+"'"));}
return;}var zfwu=null;var zfwv=null;var zfww=null;var zfwx=null;zfwx=this.zfux(zfwm,zfwn,zfju);if(!zfwx){return false;}
if(zfwx&&zfwx[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"]," Cannot move shared folder"));}
return;}zfwu=this.zfwy(zfwm,zfwn,zfju);if(!zfwu){return false;}
if(zfwn==ztk["RfItemType_Folder"]){zfwv=this.zfve(this.zfsq(),zfwq,zfrg);if(zfwv){if(zfwv[RfapiJS.ITEM_CHILDS_PROP]&&zfwv[RfapiJS.ITEM_CHILDS_PROP].length>0){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,"Cannot move file: Directory not empty: "+zfwq,undefined,undefined,"LocalErr"));}
return;}}var zfwz=zfwq.lastIndexOf("/");var zfxa=zfwq.substr(0,zfwz);if(zfxa=="/"){zfxa=zfrg;}
zfww=this.zfve(this.zfsq(),zfxa,zfrg);}else if(zfwn==ztk["RfItemType_Login"]||(zfwn==ztk["RfItemType_Bookmark"])||(zfwn==ztk["RfItemType_Identity"])||(zfwn==ztk["RfItemType_Contact"])||(zfwn==ztk["RfItemType_Safenote"])||(zfwn==ztk["RfItemType_SearchCard"])||(zfwn==ztk["RfItemType_BlockingPasscard"])){var zfxa=this.zvc(zfwq);zfww=this.zfve(this.zfsq(),zfxa,zfrg);}
if(!zfww){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqd,undefined,undefined,"NotFound"));}
return;}var zfxb="";var zfxc=zfww[RfapiJS.ITEM_CHILDS_PROP];if(!zfxc){zfww[RfapiJS.ITEM_CHILDS_PROP]=zfxc=[];}
var zfxd=zfwu[RfapiJS.ITEM_CHILDS_PROP];if(!zfxd){zfwu[RfapiJS.ITEM_CHILDS_PROP]=zfxd=[];}
if(zfwr==ztk["RfItemType_Folder"]){if(zfwv){zfxb=zfwv[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP];}
else{zfxb=zfwq.substr(zfwq.lastIndexOf("/")+1);}}else{var zbvu=zfwq.substring(zfwq.lastIndexOf("/")+1);zfxb=zbvu;}
var zfxe=false;var zfxf=this.zcsd(zfxb,zfwr,zfxc,true);var zfxg=zfxf["index"];var zfxh=zfxf["type"];if(zfxg==-1){if(zfwr==ztk["RfItemType_Folder"]){zfxe=true;}
}else{if((zfwr!=zfxh)&&(zfxh==ztk["RfItemType_Folder"])){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"],"Folder with the same name already exists in destination path"));}
return false;}}var zfxi=this.zfxj(zfwx,zfwn,zfwu);if(zfxi==-1){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+zfwm,undefined,undefined,"NotFound"));}
return;}if(zfwr==ztk["RfItemType_Folder"]){if(zfxe){var zfb=new Object();zfb[RfapiJS.ITEM_CHILDS_PROP]=[];zfb[RfapiJS.ITEM_INFO_PROP]={}
;zfb[RfapiJS.ITEM_INFO_PROP][zfqp]=0;zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_ISFOLDER_PROP]=true;zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfxb;var zfwa=this.getTime();zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_MODTIME_PROP]=zfwa;zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_CRETIME_PROP]=zfwa;if(zfwx[RfapiJS.ITEM_CHILDS_PROP]){for(var zcw=0;zcw<zfwx[RfapiJS.ITEM_CHILDS_PROP].length;zcw++){zawd.zfsm(zfwx[RfapiJS.ITEM_CHILDS_PROP][zcw],zfb[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);}
}zawd.zfsm(zfb,zfww[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);}
else{if(zfwx[RfapiJS.ITEM_CHILDS_PROP]){for(var zcw=0;zcw<zfwx[RfapiJS.ITEM_CHILDS_PROP].length;zcw++){zawd.zfsm(zfwx[RfapiJS.ITEM_CHILDS_PROP][zcw],zfwv[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);}
}}}else{if(zfxg==-1){var zbkb=new Object();zbkb[RfapiJS.ITEM_BODY_PROP]=zfwx[RfapiJS.ITEM_BODY_PROP];if(typeof zfwx[RfapiJS.ITEM_ENCODED_PROP]!=zfhx){zbkb[RfapiJS.ITEM_ENCODED_PROP]=zfwx[RfapiJS.ITEM_ENCODED_PROP];}
zbkb[RfapiJS.ITEM_INFO_PROP]={};zbkb[RfapiJS.ITEM_INFO_PROP][zfqp]=zfwx[RfapiJS.ITEM_INFO_PROP][zfqp];zbkb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfxb;zawd.zfsm(zbkb,zfww[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);}
else{zfxc[zfxg][RfapiJS.ITEM_BODY_PROP]=zfwx[RfapiJS.ITEM_BODY_PROP];zfxc[zfxg][RfapiJS.ITEM_INFO_PROP][zfqp]=zfwx[RfapiJS.ITEM_INFO_PROP][zfqp];}
}var zftg=[];if(!zfwl){zfxi=this.zfxj(zfwx,zfwn,zfwu);zfxd.splice(zfxi,1);if(zfwt!=zfwp){this.zfss(zfwo['id']);zftg.push(zfwo['id']);}
}this.zfss(zfws['id']);zftg.push(zfws['id']);if(typeof(zfjt)!=zfhx){zfjt(zcue,true,zftg);}
};zfrx.prototype[zfrs]=function(zfuu,zfjt,zfju){var path=zfuu[zfqu][RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(path,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+path));}
return;}var zcda=zfuu[zfqu][RfapiJS.ITEMINFO_TYPE_PROP];if(typeof(zcda)!=zfhx){}
else if((zcda==ztk["RfItemType_Login"])||(zcda==ztk["RfItemType_Bookmark"])||(zcda==ztk["RfItemType_Identity"])||(zcda==ztk["RfItemType_Contact"])||(zcda==ztk["RfItemType_Safenote"])||(zcda==ztk["RfItemType_SearchCard"])||(zcda==ztk["RfItemType_BlockingPasscard"])){}
else{if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"]," Invalid type:"+zcda));}
return;}var zfxk=this.zfux(path,zcda);if(!zfxk){if(zcda==ztk["RfItemType_Folder"]){if(typeof(zfjt)!=zfhx){zfjt(zcue,false,[]);}
return true;}else if(zcda==ztk["RfItemType_Login"]||(zcda==ztk["RfItemType_Bookmark"])||(zcda==ztk["RfItemType_Identity"])||(zcda==ztk["RfItemType_Contact"])||(zcda==ztk["RfItemType_Safenote"])||(zcda==ztk["RfItemType_SearchCard"])||(zcda==ztk["RfItemType_BlockingPasscard"])){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+path,undefined,undefined,"NotFound"));}
return false;}}if(zfxk&&zcda==ztk["RfItemType_Folder"]&&zfxk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_WrongParams"]," Cannot delete shared folder"));}
return;}var zvf=this.zfwy(path,zcda,zfju);if(!zvf){return false;}
var zfir=this.zfvd(path,zcda);if(!zfir){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],"Cannot determine account name."));}
return false;}var zfvy=zfir[RfapiJS.NAME_PROP];var zcks=this.zfxj(zfxk,zcda,zvf);if(zcks==-1){if(zcda==ztk["RfItemType_Folder"]){if(typeof(zfjt)!=zfhx){zfjt(zcue,false,[]);}
}else{if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+path,undefined,undefined,"NotFound"));}
}return;}zvf[RfapiJS.ITEM_CHILDS_PROP].splice(zcks,1);this.zfss(zfir['id']);var zftg=[];zftg.push(zfir['id']);if(typeof(zfjt)!=zfhx){zfjt(zcue,true,zftg);}
return;};zfrx.prototype[zfrq]=function(zfuu,zfjt,zfju){var zvd=this.zfsq();var zfxl=zvd[RfapiJS.ITEM_CHILDS_PROP];if(zfxl){for(var zcw=0;zcw<zfxl.length;zcw++){var zgk=zfxl[zcw];var zfsv=zgk[RfapiJS.ITEM_INFO_PROP];if(zfsv[RfapiJS.ITEM_SHARED_PROP]){continue;}
zfxl.splice(zcw,1);zcw--;}}this.zfss(this.zfsb);var zftg=[];zftg.push(this.zfsb);if(typeof(zfjt)!=zfhx){zfjt(zcue,true,zftg);}
return true;};var zfxm=30;zfrx.prototype[zfrr]=function(zfuu,zfjt,zfju){var zbre=zfuu[zfqu][zfqz];if(!this.zfuw(zbre,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+zbre));}
return false;}var zfir=this.zfvd(zbre,ztk["RfItemType_Folder"]);if(!zfir){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],"Cannot determine account name."));}
return false;}var zfvy=zfir[RfapiJS.NAME_PROP];var zvf=this.zfwy(zbre,ztk["RfItemType_Folder"],zfju);if(!zvf){return false;}
if(zbre.match(new RegExp("\/","g")).length>zfxm){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],"Creation of more than 30 subfolders is prohibited"));}
return false;}var zfxn=zbre.substring(zbre.lastIndexOf("/")+1);var zfxl=zvf[RfapiJS.ITEM_CHILDS_PROP];if(!zfxl){zvf[RfapiJS.ITEM_CHILDS_PROP]=zfxl=[];}
var zfxo=false;for(var zcw=0;zcw<zfxl.length;zcw++){var zgk=zfxl[zcw];if(zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP].toLowerCase()==zfxn.toLowerCase()){zfxo=true;break;}
}if(zfxo){zcte("Repository.CreateFolder. File/Folder already exists '"+zbre+"'",zwf,zctf["SPECIAL_CASE"]);if(typeof(zfjt)!=zfhx){zfjt(zcue,false,[]);}
return;}var zfb=new Object();zfb[RfapiJS.ITEM_CHILDS_PROP]=[];zfb[RfapiJS.ITEM_INFO_PROP]={}
;zfb[RfapiJS.ITEM_INFO_PROP][zfqp]=0;zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_ISFOLDER_PROP]=true;zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfxn;var zfwa=this.getTime();zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_MODTIME_PROP]=zfwa;zfb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_CRETIME_PROP]=zfwa;zvf[RfapiJS.ITEM_CHILDS_PROP]=zawd.zfsm(zfb,zvf[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);this.zfss(zfir['id']);var zftg=[];zftg.push(zfir['id']);if(typeof(zfjt)!=zfhx){zfjt(zcue,true,zftg);}
return;};zfrx.prototype.zfxp=function(zfuu,zfjt,zfju){var item=zfuu[zfqu]["item"];var zbre=item[RfapiJS.ITEMINFO_PATH_PROP];if(!this.zfuw(zbre,true)){if(typeof(zfju)!=zfhx){zfju(new zfpw(zfhs["RfErr_InvalidPath"],zfqg+zbre));}
return false;}var zcda=item[RfapiJS.ITEMINFO_TYPE_PROP];zcda=parseInt(zcda);var zvf=null;if(zcda==8){zvf=this.zfwy(zbre,ztk["RfItemType_Folder"],zfju);}
else{var zdwx=zbre.substr(0,zbre.lastIndexOf("/")+1);if(zdwx.endsWith("/")){zdwx=zdwx.substr(0,zdwx.length-1);}
if(zdwx=="/"){zdwx="";}zvf=this.zfux(zdwx,ztk["RfItemType_Folder"],zfju);}
if(!zvf){return false;}var zfxq=zbre.substring(zbre.lastIndexOf("/")+1);var zbkb=new Object();zbkb[RfapiJS.ITEM_INFO_PROP]={}
;zbkb[RfapiJS.ITEM_INFO_PROP][zfqp]=item[RfapiJS.ITEMINFO_SIZE_PROP];zbkb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]=zfxq;zbkb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_MODTIME_PROP]=item[RfapiJS.ITEMINFO_MODTIME_PROP];zbkb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_CRETIME_PROP]=item[RfapiJS.ITEMINFO_CREATETIME_PROP];if(zcda==8){zbkb[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_ISFOLDER_PROP]=true;zbkb[RfapiJS.ITEM_CHILDS_PROP]=[];}
else{zbkb[RfapiJS.ITEM_BODY_PROP]=JSON.stringify(zfuu[zfqu]["data"]);}
zawd.zfsm(zbkb,zvf[RfapiJS.ITEM_CHILDS_PROP],[RfapiJS.ITEM_INFO_PROP,RfapiJS.ITEM_NAME_PROP]);var zftg=[];zftg.push(this.zfsb);if(typeof(zfjt)!=zfhx){zfjt(zcue,true,zftg);}
return;};zfrx.prototype.zfvd=function(path,zcda){if(path.startsWith("/")){path=path.substr(1);}
var zep=path.indexOf("/");var zfxr="";if(zep==-1){if(zcda!=ztk["RfItemType_Folder"]){return{"id":this.zfsb,"name":this.zfsb,"isShared":false,"readOnly":false,"showPasswords":true,"disabled":false,"isManager":false,"isAdmin":false,"licenseExpired":false,"isAllowedIP":true}
;}else{zfxr=path;}}else{zfxr=path.substr(0,zep);}var zvd=this.zfsq();var zfxl=zvd[RfapiJS.ITEM_CHILDS_PROP];if(typeof zfxl==zfhx){return{"id":this.zfsb,"name":this.zfsb,"isShared":false,"readOnly":false,"showPasswords":true,"disabled":false,"isManager":false,"isAdmin":false,"licenseExpired":false,"isAllowedIP":true}
;}for(var zcw=0;zcw<zfxl.length;zcw++){var zgk=zfxl[zcw];if(zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==zfxr){if(typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]==zfhx){return{"id":this.zfsb,"name":this.zfsb,"isShared":false,"readOnly":false,"showPasswords":true,"disabled":false,"isManager":false,"isAdmin":false,"licenseExpired":false,"isAllowedIP":true}
;}else{var zdbd=typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["disabled"]==zfhx?false:zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["disabled"];var zfxs=typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["showPasswords"]==zfhx?false:zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["showPasswords"];var zcjg=typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["readOnly"]==zfhx?false:zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["readOnly"];var zfxt=typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["isManager"]==zfhx?false:zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["isManager"];var zfxu=typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["isAdmin"]==zfhx?false:zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["isAdmin"];var zfxv=typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["licenseExpired"]==zfhx?false:zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP]["licenseExpired"];var zfxw=typeof zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP]["isAllowedIP"]==zfhx?true:zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNTINFO_PROP]["isAllowedIP"];return{"id":zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_SHARED_PROP][RfapiJS.ACCOUNT_ID_PROP],"name":zgk[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP],"isShared":true,"showPasswords":zfxs,"disabled":zdbd,"readOnly":zcjg,"isManager":zfxt,"isAdmin":zfxu,"licenseExpired":zfxv,"isAllowedIP":zfxw}
;}}}return{"id":this.zfsb,"name":this.zfsb,"isShared":false,"readOnly":false,"showPasswords":true,"disabled":false,"isManager":false,"isAdmin":false,"licenseExpired":false,"isAllowedIP":true}
;};zfrx.prototype.zvq=function(path,zfb,zbjl,zcvc,zfr,zfvo,zgv,zfxx,zfxy){for(var zcw=0;zcw<zfb[RfapiJS.ITEM_CHILDS_PROP].length;zcw++){var zcry=zfb[RfapiJS.ITEM_CHILDS_PROP][zcw];var zfxz=zcry[RfapiJS.ITEM_INFO_PROP];var zfya=(typeof(zfxz[RfapiJS.ITEM_ISFOLDER_PROP])!=zfhx)&&(zfxz[RfapiJS.ITEM_ISFOLDER_PROP]==true);var zfyb=!zfya;var zfyc=zfxz[RfapiJS.ITEM_NAME_PROP];if(zfyb){var zfyd=zfyc.lastIndexOf(".");var zfcl=zfyc.substr(zfyc.lastIndexOf("."));var zbqo=zawd.zfuv(zfcl);if(zze(zbjl,zbqo)){var zfvw=this.zfvx(zcry,path+"/"+zfyc,zbqo,zfr,zfxy,zfvo);zgv.push(zfvw);}
}else if(zfya){if(zze(zbjl,ztk["RfItemType_Folder"])){var zfvw=this.zfvx(zcry,path+"/"+zfyc,ztk["RfItemType_Folder"],zfr,zfxy,zfvo);zgv.push(zfvw);}
}if(zcvc&&(typeof(zcry[RfapiJS.ITEM_CHILDS_PROP])!=zfhx)){var zfye=path+"/"+zfyc;this.zvq(zfye,zcry,zbjl,zcvc,zfr,zfvo,zgv,zfxx,zfxy);}
}};function zze(arr,zvy){for(var zcw=0;zcw<arr.length;zcw++){if(arr[zcw]==zvy)return true;}
}zfrx.prototype.zfve=function(zfb,zcrx,zcdc){if(zcdc==zcrx){return zfb;}
if(!zfb[RfapiJS.ITEM_CHILDS_PROP]){return null;}var zbxk=zfb[RfapiJS.ITEM_CHILDS_PROP].length;if(zbxk){var zgv=null;for(var zgg=0;zgv==null&&zgg<zbxk;zgg++){var zfyf=zfb[RfapiJS.ITEM_CHILDS_PROP][zgg];if(zfyf[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_ISFOLDER_PROP]){var zcrz=zcdc+"/"+zfyf[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP];zgv=this.zfve(zfyf,zcrx,zcrz);}
}return zgv;}return null;};zfrx.prototype.zvc=function(zbre){var zcsa=zbre.lastIndexOf("/");var zcsb=zfrg;if(zcsa==0){zcsb=zfrg;}
else{zcsb=zbre.substring(0,zbre.lastIndexOf("/"));}
return zcsb;};zfrx.prototype.zfuw=function(path,zfyg){var zbxk=path.length;if((path==zfrg)&&zfyg){return false;}
if(path.startsWith("/")&&zbxk==1){return false;}if(!path.startsWith("/")&&zbxk>1){return false;}
if(path.endsWith("/")){return false;}return true;}
;zfrx.prototype.zfwy=function(zbre,zcda,zfju){var zvf=null;if(zcda==ztk["RfItemType_Folder"]){var zdwx=zbre.substr(0,zbre.lastIndexOf("/")+1);if(zdwx.endsWith("/")){zdwx=zdwx.substr(0,zdwx.length-1);}
if(zdwx=="/"){zdwx=zfrg;}zvf=this.zfve(this.zfsq(),zdwx,zfrg);if(!zvf){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqd,undefined,undefined,"NotFound"));}
return null;}return zvf;}var zcsb=this.zvc(zbre);zvf=this.zfve(this.zfsq(),zcsb,zfrg);if(!zvf){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqd,undefined,undefined,"NotFound"));}
return null;}return zvf;};zfrx.prototype.zfux=function(zbre,zcda,zfju,zfyh){var zbvu=zbre.substring(zbre.lastIndexOf("/")+1);if(zcda==ztk["RfItemType_Folder"]){var zfb=this.zfve(this.zfsq(),zbre,zfrg);if(!zfb){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+zbre+" Type:"+zcda,undefined,undefined,"NotFound"));}
return null;}return zfb;}var zvf=null;zvf=this.zfve(this.zfsq(),this.zvc(zbre),zfrg);if(!zvf){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+zbre,undefined,undefined,"NotFound"));}
return null;}var zgh=typeof zvf[RfapiJS.ITEM_CHILDS_PROP]==zfhx?[]:zvf[RfapiJS.ITEM_CHILDS_PROP];var zfxf=this.zcsd(zbvu,zcda,zgh,zfyh);var zcks=zfxf["index"];if(zcks==-1){if(typeof(zfju)!=zfhx){zfju(new zfpw(undefined,zfqb+zbre+" Type:"+zcda,undefined,undefined,"NotFound"));}
return null;}return zvf[RfapiJS.ITEM_CHILDS_PROP][zcks];}
;zfrx.prototype.zfxj=function(item,zcda,zvf){var zbvu=item[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP];var zcsf=zvf[RfapiJS.ITEM_CHILDS_PROP];var zcks=-1;if(zcsf){for(var zcw=0;zcw<zcsf.length;zcw++){var zcry=zcsf[zcw];if((zcry[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP]==zbvu)){zcks=zcw;break;}
}}return zcks;};zfrx.prototype.zcsd=function(zbvu,zcda,zcsf,zfyh){var zcks=-1;var zceq=-1;var zfyi=(typeof zfyh==zfhx)?false:zfyh;zbvu=zfyi?zbvu.toLowerCase():zbvu;for(var zcw=0;zcw<zcsf.length;zcw++){var zcry=zcsf[zcw];var zfyj=zfyi?zcry[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP].toLowerCase():zcry[RfapiJS.ITEM_INFO_PROP][RfapiJS.ITEM_NAME_PROP];if(zfyj==zbvu){zcks=zcw;if((typeof zcry[RfapiJS.ITEM_CHILDS_PROP]!=zfhx)||(typeof zcry[RfapiJS.ITEM_INFO_PROP]["Shared"]!=zfhx)||(zcry[RfapiJS.ITEM_INFO_PROP]["F"])){zceq=ztk["RfItemType_Folder"];}
else{var zfcl=zfyj.substr(zfyj.lastIndexOf("."));zceq=zawd.zfuv(zfcl);}
break;}}return{"index":zcks,"type":zceq};};var zfvm="protected";zfrx.prototype.zfvx=function(zfyk,path,zcda,zfr,zfuc,zfvo){var zfvw=new Object();try{var zfxz=zfyk[RfapiJS.ITEM_INFO_PROP];if(!zfuc){zfvw[RfapiJS.ITEMINFO_CREATETIME_PROP]=typeof(zfxz[RfapiJS.ITEM_CRETIME_PROP])!=zfhx?zfxz[RfapiJS.ITEM_CRETIME_PROP]:0;zfvw[RfapiJS.ITEMINFO_MODTIME_PROP]=typeof(zfxz[RfapiJS.ITEM_MODTIME_PROP])!=zfhx?zfxz[RfapiJS.ITEM_MODTIME_PROP]:0;zfvw[RfapiJS.ITEMINFO_SIZE_PROP]=typeof(zfxz[zfqp])!=zfhx?zfxz[zfqp]:0;zfvw[RfapiJS.ITEMINFO_TYPE_PROP]=zcda;zfvw[RfapiJS.ITEMINFO_PATH_PROP]=path;if(typeof zfxz[RfapiJS.ITEM_SHARED_PROP]!=zfhx){zfvw[RfapiJS.ITEM_SHARED_PROP]=zfxz[RfapiJS.ITEM_SHARED_PROP];}
if(typeof zfyk["s"]!=zfhx){zfvw["s"]=zfyk["s"];}}if(zfr>1||zfvo){var zfuy=((typeof zfyk[RfapiJS.ITEM_ENCODED_PROP]!=zfhx)&&(zfyk[RfapiJS.ITEM_ENCODED_PROP]==true))?true:false;var body=zfyk[RfapiJS.ITEM_BODY_PROP];var zfwd=null;if(typeof(body)!=zfhx){if(zfr&zfpx["enFlags"]){var zfyl=zfuc==false?zfvm:zfqr;if(zfuy){zfvw[RfapiJS.ITEM_ENCODED_PROP]=true;body=this.zfuz(path,body,true);}
zfwd=JSON.parse(body);zfvw[zfyl]=typeof(zfwd[zfqr])!=zfhx?zfwd[zfqr]:false;}
if((zfr&zfpx["enUrls"])){if(zcda==ztk["RfItemType_Bookmark"]||zcda==ztk["RfItemType_Login"]||zcda==ztk["RfItemType_SearchCard"]){if(!zfwd){if(zfuy){zfvw[RfapiJS.ITEM_ENCODED_PROP]=true;body=this.zfuz(path,body,true);}
zfwd=JSON.parse(body);}var zfym=zfuc==false?zfqx:RfapiJS.ITEM_MATCHURL_PROP;zfvw[zfym]=typeof(zfwd[RfapiJS.ITEM_MATCHURL_PROP])!=zfhx?zfwd[RfapiJS.ITEM_MATCHURL_PROP]:"";var zfyn=zfuc==false?zfqw:RfapiJS.ITEM_GOTOURL_PROP;zfvw[zfyn]=typeof(zfwd[RfapiJS.ITEM_GOTOURL_PROP])!=zfhx?zfwd[RfapiJS.ITEM_GOTOURL_PROP]:"";}
if(zcda==ztk["RfItemType_BlockingPasscard"]){if(!zfwd){if(zfuy){zfvw[RfapiJS.ITEM_ENCODED_PROP]=true;body=this.zfuz(path,body,true);}
zfwd=JSON.parse(body);}var zfym=zfuc==false?zfqx:RfapiJS.ITEM_MATCHURL_PROP;zfvw[zfym]=typeof(zfwd[RfapiJS.ITEM_MATCHURL_PROP])!=zfhx?zfwd[RfapiJS.ITEM_MATCHURL_PROP]:"";}
}if(zfr&zfpx["enUnprotData"]){if(!zfwd){if(zfuy){zfvw[RfapiJS.ITEM_ENCODED_PROP]=true;body=this.zfuz(path,body,true);}
zfwd=JSON.parse(body);}if(zcda==ztk["RfItemType_BlockingPasscard"]){var zeo=zfuc==false?RfapiJS.ITEMDATA_BLOCK_PROP:RfapiJS.ITEMDATA_BLOCK_PROP;zfvw[zeo]=typeof(zfwd[RfapiJS.ITEMDATA_BLOCK_PROP])!=zfhx?zfwd[RfapiJS.ITEMDATA_BLOCK_PROP]:0;}
if(zcda==ztk["RfItemType_SearchCard"]){var zfyo=zfuc==false?zfqq:zfqq;zfvw[zfyo]=typeof(zfwd[zfqq])!=zfhx?zfwd[zfqq]:0;}
}if(zfr&zfpx["enUsageInfo"]){}if((zfuc)&&(zfr&zfpx["enAll"])){if(!zfwd){if(zfuy){zfvw[RfapiJS.ITEM_ENCODED_PROP]=true;body=this.zfuz(path,body,true);}
zfwd=JSON.parse(body);}if(zcda==ztk["RfItemType_Bookmark"]||zcda==ztk["RfItemType_Login"]||zcda==ztk["RfItemType_BlockingPasscard"]||zcda==ztk["RfItemType_Safenote"]||zcda==ztk["RfItemType_SearchCard"]){zfvw[RfapiJS.ITEM_NOTE_PROP]=typeof(zfwd[RfapiJS.ITEM_NOTE_PROP])!=zfhx?zfwd[RfapiJS.ITEM_NOTE_PROP]:"";}
if(zcda==ztk["RfItemType_Contact"]||zcda==ztk["RfItemType_Identity"]){zfvw[RfapiJS.ID_OPTIONS_PROP]=typeof(zfwd[RfapiJS.ID_OPTIONS_PROP])!=zfhx?zfwd[RfapiJS.ID_OPTIONS_PROP]:{}
;zfvw[RfapiJS.ID_GROUPS_PROP]=typeof(zfwd[RfapiJS.ID_GROUPS_PROP])!=zfhx?zfwd[RfapiJS.ID_GROUPS_PROP]:[];}
if(typeof zfwd[RfapiJS.ITEMDATA_FIELDS_PROP]!=zfhx){zfvw[RfapiJS.ITEMDATA_FIELDS_PROP]=[];for(var zcw=0;zcw<zfwd[RfapiJS.ITEMDATA_FIELDS_PROP].length;zcw++){zfvw[RfapiJS.ITEMDATA_FIELDS_PROP].push(zfwd[RfapiJS.ITEMDATA_FIELDS_PROP][zcw]);}
}}}}return zfvw;}catch(zdn){zwe("EXCEPTION in Repo.ConvertFromOFS  path='"+path+"' objType='"+zcda+"'  parts='"+zfr+"'  ERROR="+zdn.toString(),zwf);zfvw["error"]=zdn.toString();return zfvw;}
};zfrx.prototype.zfuz=function(zasi,zwr,zfyp){var zfyq=zfyp?"{}":"";try{if(zfyp){if(window.atob){zwr=zwr.replace(new RegExp("\\-","g"),"+");zwr=zwr.replace(new RegExp("_","g"),"/");zfyq=window.atob(zwr);zfyq=RfapiJS["Base64"].zfyr(zfyq);}
else{var zvy={"szSrc":zwr,"pbDest":undefined,"pnDestLen":0}
;RfapiJS["Base64"].zfys(zvy);var zfyt={"szSrc":zwr,"pbDest":"","pnDestLen":zvy["pnDestLen"]}
;RfapiJS["Base64"].zfys(zfyt);zfyq=zfyt["pbDest"];}
}else{if(window.btoa){zwr=RfapiJS["Base64"].zfyu(zwr);zfyq=window.btoa(zwr);zfyq=zfyq.replace(new RegExp("=","g"),"");zfyq=zfyq.replace(new RegExp("\\+","g"),"-");zfyq=zfyq.replace(new RegExp("/","g"),"_");}
else{}}}catch(zdn){zwe("EXCEPTION in Repo.base64DecodeBody while [en]decode fileName='"+zasi+"' itemBody='"+zwr+"'  ERROR="+zdn.toString(),zwf);zfyq=zfyp?"{}":"";}
return zfyq;};zfrx.prototype.getTime=function(){var zfuj=Math.round(new Date()/1000);return zfuj;}
;if(!String.prototype.startsWith){String.prototype.startsWith=function(zafb){return(this.match("^"+zafb)==zafb);}
;}if(!String.prototype.endsWith){String.prototype.endsWith=function(zafb){return(this.match(zafb+"$")==zafb);}
;}if(!String.prototype.trimLeft){String.prototype.trimLeft=function(){return this.replace(new RegExp("^\\s+"),"");}
;}if(!String.prototype.trimRight){String.prototype.trimRight=function(){return this.replace(new RegExp("\\s+$"),"");}
;}if(!String.prototype.trim){String.prototype.trim=function(){return this.trimLeft().trimRight();}
;}RfapiJS.Repository=zfrx;}).apply(RfapiJS);
